# 调试模式
debug: true
# 服务地址
host: 0.0.0.0
# 服务端口
port: 3000

# 数据库
database:
  # 类型
  type: mysql
  # 服务器地址
  host: 127.0.0.1
  # 数据库名
  name: bbs
  # 端口
  port: 3306
  # 用户名
  user: root
  # 密码
  password: root
  # 编码默认采用utf8
  charset: utf8
  # 表前缀
  prefix: rz_ 
  # 调试模式
  debug: true
  # 部署方式:0 集中式(单一服务器),1 分布式(主从服务器)
  deploy: 0

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456